name: Auto Versioning

on:
  push:
    branches:
      - master
      

jobs:
  update_version:
    runs-on: ubuntu-latest      
    name: Autoincrements Version
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python ../../version.py
