name: Auto Versioning

on:
  push:
    branches:
      - master

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Update the version
      id: update-version
      run: python ../../version.py
      shell: bash
